{% set name = "fair-research-login" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f9579242ed916ce5f0f61d05790d9dfaea79ded106a9d424393471846972cd87

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pip
    - globus-sdk

test:
  imports:
    - fair_research_login
  commands:
    - pip check

about:
  home: https://github.com/fair-research/native-login
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Provides Native App login and token storage for multiple providers

  description: |
    This package makes writing Globus scripts and clients a 
    breeze! Easily setup token management and local server 
    login with a few lines of code. Easily extend components 
    as your app grows and requires its own config.
  doc_url: https://github.com/fair-research/native-login
  dev_url: https://github.com/fair-research/native-login

extra:
  recipe-maintainers:
    - jan-janssen
